### PR TITLE
extend documentation: add_new_kernel

### PR DESCRIPTION
**Pull request by thawn**
This is a first draft extending the documentation for adding a new kernel. I added the sections `Add a new method to the Clesperanto class gateway` and `Add a valid test case`.

### CODE REVIEW

**Comment by StRigaud** [comment]
Thanks for the help!

Thinking about splitting the markdown file into smaller ones, as follow:
- how to contribute
- create a new class
  - header
  - source
  - gateway
- create a test
  - source
  - cmakelist

Large and long text file make people don't want to read.

**Comment by thawn** [comment]
@StRigaud that sounds like an excellent idea. How about adding "How to contribute" as a new section to the [guidelines document](https://github.com/clEsperanto/CLIc_prototype/blob/master/docs/guidelines.md)? It seems to fit well there (and that document is not very long yet).

**Comment by thawn** [comment]
@StRigaud How about splitting the document into two like I just committed? (assuming we add a new how to contribute section to the guidelines)

**Comment by StRigaud** [comment]
Yes this is good. No need to over-split neither :wink: 

> How about adding "How to contribute" as a new section to the [guidelines document](https://github.com/clEsperanto/CLIc_prototype/blob/master/docs/guidelines.md)? It seems to fit well there (and that document is not very long yet).

Yes! the guideline a here as a summary top file from which we can link to sub-documentation.

**Comment by StRigaud** [comment]
> Base: **77.88**% // Head: **78.01**% // Increases project coverage by **`+0.13%`**

Since when writing doc increase coverage?

**Comment by thawn** [comment]
I was also surprised by this. 

I guess, writing documentation decreases the percentage of code - hence the test coverage of the entire project (code + documentation) is increased - still funny though ;-)

**Comment by StRigaud** [comment]
a vicious incentive for pushing dev into writing documentation ;)

**Comment by StRigaud** [comment]
Rearrange of the doc, plus added a few more on coding guideline and clang-format.

Don't know if we need more for now.

**Comment by thawn** [comment]
I just read your changes - looks great to me!
ready to merge from my side 👍

**Review by StRigaud — APPROVED** [review]

**Pull request merged**
