### PR TITLE
Ocl buffer image interoperability

### PR DESCRIPTION
**Pull request by StRigaud**
Update core code to enable `image` along with `buffer` data type for kernels.
This comes with a reshape of 

- the data class tree
- the opencl kernel from clij to make them nDimensional

### CODE REVIEW

**Comment by StRigaud** [comment]
Sobel kernel is failing as it has not been updated yet in CLIJ repository.

**Comment by StRigaud** [comment]
Currently missing cle_sobel.h generated from sobel.cl, not yet updated to the new clesperanto standard.
We set the test to fail.

Need to check if all kernels works correctly no matter the input and output type being buffer or image. This may require an update and rewrite of some of the tests.

**Comment by StRigaud** [comment]
I raise the possibility that `cl_image` is not available on the current Github server running the CI ...

**Comment by StRigaud** [comment]
For unknown reasons, the test to run some kernels on images fails when data type are `int` and `uint`. 
No errors is raised on my local machine, I do not know why it raised such issue.

**Comment by StRigaud** [comment]
Merge is ready!

Incoming soon :love_you_gesture:

**Comment by StRigaud** [comment]
Quick benchmark test for the fun on my :snail: GTX 1050 Ti :snail:, values are average over 10 runs

**Gaussian sigma=10 on a 512x512x100 float:**
- C++ CLIc buffer - 0.3 sec +15%
- C++ CLIc image - 0.26 sec :rocket: 
- pyClesperanto - 0.38 sec +46%

**Mean box radius=10 on a 512x512x100 float:**
- C++ CLIc buffer - 0.057 sec +16%
- C++ CLIc image - 0.049 sec :rocket: 
- pyClesperanto - 0.078 +59% sec

All of this can change when we will start to apply wrapper of course but still it is satisfying!

**Comment by haesleinhuepf** [comment]
> **Gaussian sigma=10 on a 512x512x100 float:**
> 
> * C++ CLIc buffer - 0.3 sec +15%
> * C++ CLIc image - 0.26 sec 🚀
> * pyClesperanto - 0.38 sec +46%
> 
> **Mean box radius=10 on a 512x512x100 float:**
> 
> * C++ CLIc buffer - 0.057 sec +16%
> * C++ CLIc image - 0.049 sec 🚀
> * pyClesperanto - 0.078 +59% sec

Amazing! You will turn mit into a C++-Bio-image analyst soon. I can feel it.

Have a great weekend! :-)

**Pull request merged**
